version: '3.4'

services:
  web-app:
    build:
      context: "./"
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - /app/src/server/node_modules # https://stackoverflow.com/a/37898591 (ensuring that we don't bind to local node_modules folder)
    ports:
      - "3000:3000"
      - "24679:24679" # vite port
    networks:
      - memixit_network

networks:
  memixit_network:
    external: true
